# Generated by Django 5.1.6 on 2025-02-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=30)),
                ('prio', models.CharField(max_length=30)),
                ('prioImg', models.CharField(max_length=80)),
                ('taskCategory', models.CharField(max_length=30)),
            ],
        ),
    ]
