# Generated by Django 5.1.6 on 2025-02-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_person_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.member'),
        ),
    ]
