# Generated by Django 5.1.6 on 2025-02-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.member'),
        ),
    ]
