# Generated by Django 5.1.6 on 2025-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_subtasks_state_alter_task_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Subtasks',
        ),
    ]
