# Generated by Django 5.1.6 on 2025-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_subtasks_delete_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskContacts',
            field=models.JSONField(default=list),
        ),
    ]
